from pathlib import Path

import pandas as pd


# Project folders
PROJECT_ROOT = Path(__file__).resolve().parents[1]
RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw"
CLEANED_DATA_DIR = PROJECT_ROOT / "data" / "cleaned"


# Files generated by scripts/generate_data.py
CSV_FILES = [
    "territories.csv",
    "hcps.csv",
    "medical_reps.csv",
    "products.csv",
    "hcp_calls.csv",
    "sales.csv",
    "campaigns.csv",
    "campaign_engagement.csv",
]


# Date columns are converted to a consistent YYYY-MM-DD format.
DATE_COLUMNS = {
    "medical_reps.csv": ["hire_date"],
    "products.csv": ["launch_date"],
    "hcp_calls.csv": ["call_date", "next_call_planned_date"],
    "sales.csv": ["sale_date"],
    "campaigns.csv": ["start_date", "end_date"],
    "campaign_engagement.csv": ["engagement_date"],
}


# Numeric columns are converted safely. Invalid values become 0.
NUMERIC_COLUMNS = {
    "territories.csv": ["market_potential", "target_hcps"],
    "hcps.csv": ["years_practicing", "patient_volume"],
    "medical_reps.csv": ["experience_years", "monthly_call_target", "sales_target"],
    "products.csv": ["unit_price", "margin_percent"],
    "hcp_calls.csv": ["call_duration_minutes", "engagement_score"],
    "sales.csv": [
        "units_sold",
        "gross_sales",
        "discount_amount",
        "net_sales",
    ],
    "campaigns.csv": ["budget"],
    "campaign_engagement.csv": ["response_score"],
}


def standardize_column_names(dataframe):
    """Make column names consistent and analysis-friendly."""
    dataframe.columns = (
        dataframe.columns.str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )
    return dataframe


def strip_text_columns(dataframe):
    """Remove leading and trailing spaces from text values."""
    for column in dataframe.columns:
        if pd.api.types.is_object_dtype(dataframe[column]) or pd.api.types.is_string_dtype(
            dataframe[column]
        ):
            dataframe[column] = dataframe[column].astype("string").str.strip()

    return dataframe


def clean_date_columns(dataframe, filename):
    """Convert date columns to YYYY-MM-DD strings."""
    for column in DATE_COLUMNS.get(filename, []):
        if column in dataframe.columns:
            parsed_dates = pd.to_datetime(dataframe[column], errors="coerce")
            dataframe[column] = parsed_dates.dt.strftime("%Y-%m-%d")

    return dataframe


def clean_numeric_columns(dataframe, filename):
    """Convert numeric columns to numbers and fill invalid values with 0."""
    for column in NUMERIC_COLUMNS.get(filename, []):
        if column in dataframe.columns:
            dataframe[column] = pd.to_numeric(dataframe[column], errors="coerce").fillna(0)

    return dataframe


def handle_missing_values(dataframe, filename):
    """Fill missing values in a simple, safe way for beginner analytics work."""
    date_columns = set(DATE_COLUMNS.get(filename, []))
    numeric_columns = set(NUMERIC_COLUMNS.get(filename, []))

    for column in dataframe.columns:
        if column in numeric_columns:
            dataframe[column] = dataframe[column].fillna(0)
        elif column in date_columns:
            # Keep missing dates blank instead of inventing a date.
            dataframe[column] = dataframe[column].fillna("")
        else:
            dataframe[column] = dataframe[column].fillna("Unknown")

    return dataframe


def clean_file(filename):
    """Read, clean, and save one CSV file."""
    input_path = RAW_DATA_DIR / filename
    output_path = CLEANED_DATA_DIR / filename

    dataframe = pd.read_csv(input_path)
    raw_row_count = len(dataframe)

    dataframe = standardize_column_names(dataframe)
    dataframe = strip_text_columns(dataframe)
    dataframe = clean_date_columns(dataframe, filename)
    dataframe = clean_numeric_columns(dataframe, filename)
    dataframe = handle_missing_values(dataframe, filename)
    dataframe = dataframe.drop_duplicates()

    cleaned_row_count = len(dataframe)
    duplicates_removed = raw_row_count - cleaned_row_count

    dataframe.to_csv(output_path, index=False)

    return raw_row_count, cleaned_row_count, duplicates_removed


def main():
    """Clean all raw PharmaPulse CSV files."""
    CLEANED_DATA_DIR.mkdir(parents=True, exist_ok=True)

    print("Cleaning PharmaPulse raw data files:")

    for filename in CSV_FILES:
        raw_row_count, cleaned_row_count, duplicates_removed = clean_file(filename)
        print(
            f"- {filename}: {raw_row_count:,} raw rows, "
            f"{cleaned_row_count:,} cleaned rows, "
            f"{duplicates_removed:,} duplicates removed"
        )


if __name__ == "__main__":
    main()
